[32m2022-01-30 00:01:32.231[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 00:01:32.239[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 00:01:32.246[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36m<module>[0m:[36m38[0m - [31m[1mAn error has been caught in function '<module>', process 'MainProcess' (1844), thread 'MainThread' (140510449694528):[0m
[33m[1mTraceback (most recent call last):[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m38[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7fcb0d6435e0>[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m28[0m, in [35mmain[0m
    [1mprint[0m[1m([0m[1mlen[0m[1m([0m[1mdf[0m[1m)[0m[1m)[0m
    [36m          â”” [0m[36m[1mNone[0m

[31m[1mTypeError[0m:[1m object of type 'NoneType' has no len()[0m
[32m2022-01-30 00:01:59.375[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 00:01:59.384[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 00:01:59.391[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m30[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 00:02:24.291[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 00:02:24.300[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 00:02:24.347[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m31[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 00:05:54.721[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 00:05:54.730[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 00:05:54.771[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m32[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 00:06:51.941[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 00:06:51.950[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 00:06:51.996[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m32[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 00:07:09.706[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 00:07:09.715[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 00:07:09.720[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m26[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (1999), thread 'MainThread' (139782931371840):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m40[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f21a9eb9670>[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m26[0m, in [35mmain[0m
    [1mdf[0m [35m[1m=[0m [1mload_dataframe[0m[1m([0m[1mdonor_positive_only[0m[1m,[0m [34m[1m1[0m[1m)[0m
    [36m     â”‚              â”” [0m[36m[1marray(['CTCCGAAGTAGGATT', 'TCAGAAGGTGAGGGC', 'TTGGAAGGTTCGCAG', ...,[0m
    [36m     â”‚                [0m[36m[1m       'CCTGCTGGTACGTGG', 'TCTGCCCGTAAGCAC', 'AGGCCAGGTA...[0m
    [36m     â”” [0m[36m[1m<function load_dataframe at 0x7f21a9eb43a0>[0m

  File "[32m/home/santa/2021z/uma/pro/repo/UMA_Projekt/src/miscellaneous/[0m[32m[1mdata_loader.py[0m", line [33m14[0m, in [35mload_dataframe[0m
    [1mvalue[0m [35m[1m=[0m [1m[[0m[1mord[0m[1m([0m[1mlabel[0m[1m)[0m [35m[1mfor[0m [1ms[0m [35m[1min[0m [1mstrings[0m[1m][0m[1m)[0m  [30m[1m# add label[0m
    [36m             â”‚               â”” [0m[36m[1marray(['CTCCGAAGTAGGATT', 'TCAGAAGGTGAGGGC', 'TTGGAAGGTTCGCAG', ...,[0m
    [36m             â”‚                 [0m[36m[1m       'CCTGCTGGTACGTGG', 'TCTGCCCGTAAGCAC', 'AGGCCAGGTA...[0m
    [36m             â”” [0m[36m[1m1[0m

  File "[32m/home/santa/2021z/uma/pro/repo/UMA_Projekt/src/miscellaneous/[0m[32m[1mdata_loader.py[0m", line [33m14[0m, in [35m<listcomp>[0m
    [1mvalue[0m [35m[1m=[0m [1m[[0m[1mord[0m[1m([0m[1mlabel[0m[1m)[0m [35m[1mfor[0m [1ms[0m [35m[1min[0m [1mstrings[0m[1m][0m[1m)[0m  [30m[1m# add label[0m
    [36m             â”‚          â”” [0m[36m[1m'CTCCGAAGTAGGATT'[0m
    [36m             â”” [0m[36m[1m1[0m

[31m[1mTypeError[0m:[1m ord() expected string of length 1, but int found[0m
[32m2022-01-30 00:07:09.729[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36m<module>[0m:[36m40[0m - [31m[1mAn error has been caught in function '<module>', process 'MainProcess' (1999), thread 'MainThread' (139782931371840):[0m
[33m[1mTraceback (most recent call last):[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m40[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f21a9eb9670>[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m28[0m, in [35mmain[0m
    [1mprint[0m[1m([0m[1mlen[0m[1m([0m[1mdf[0m[1m)[0m[1m)[0m
    [36m          â”” [0m[36m[1mNone[0m

[31m[1mTypeError[0m:[1m object of type 'NoneType' has no len()[0m
[32m2022-01-30 00:07:53.142[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 00:07:53.151[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 00:07:53.189[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m32[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 00:09:49.521[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 00:09:49.531[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 00:09:49.579[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m33[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 00:11:03.230[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 00:11:03.239[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 00:11:03.289[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36m<module>[0m:[36m41[0m - [31m[1mAn error has been caught in function '<module>', process 'MainProcess' (2109), thread 'MainThread' (139738632124224):[0m
[33m[1mTraceback (most recent call last):[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m41[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f17597ab550>[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m31[0m, in [35mmain[0m
    [1mprint[0m[1m([0m[1mdf[0m[1m[[0m[36m'5'[0m[1m][0m[35m[1m.[0m[1munique[0m[1m([0m[1m)[0m [35m[1min[0m [1m[[0m[36m'A'[0m[1m,[0m [36m'C'[0m[1m,[0m [36m'G'[0m[1m,[0m [36m'T'[0m[1m][0m[1m)[0m
    [36m      â”” [0m[36m[1m      0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15[0m
    [36m        [0m[36m[1m0     C  T  C  C  G  A  A  G  T  A  G  G  A  T  T  1[0m
    [36m        [0m[36m[1m1     T  C  A  G  A...[0m

[31m[1mValueError[0m:[1m The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()[0m
[32m2022-01-30 00:16:39.904[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 00:16:39.914[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 00:16:39.955[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m33[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 00:17:05.955[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 00:17:05.964[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 00:17:06.005[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36m<module>[0m:[36m41[0m - [31m[1mAn error has been caught in function '<module>', process 'MainProcess' (2253), thread 'MainThread' (140140377327424):[0m
[33m[1mTraceback (most recent call last):[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m41[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f74e35c0550>[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m31[0m, in [35mmain[0m
    [1mprint[0m[1m([0m[1mset[0m[1m([0m[1mdf[0m[1m[[0m[36m'5'[0m[1m][0m[35m[1m.[0m[1munique[0m[1m([0m[1m)[0m[1m)[0m [35m[1min[0m [1mset[0m[1m([0m[36m'A'[0m[1m,[0m [36m'C'[0m[1m,[0m [36m'G'[0m[1m,[0m [36m'T'[0m[1m)[0m[1m)[0m
    [36m          â”” [0m[36m[1m      0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15[0m
    [36m            [0m[36m[1m0     C  T  C  C  G  A  A  G  T  A  G  G  A  T  T  1[0m
    [36m            [0m[36m[1m1     T  C  A  G  A...[0m

[31m[1mTypeError[0m:[1m set expected at most 1 argument, got 4[0m
[32m2022-01-30 00:17:20.570[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 00:17:20.579[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 00:17:20.620[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m33[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 00:19:31.335[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 00:19:31.344[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 00:19:31.391[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m34[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 00:20:45.200[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 00:20:45.209[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 00:20:45.252[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m35[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 00:29:03.840[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 00:29:03.849[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 00:29:03.894[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m35[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 00:32:36.528[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 00:32:36.568[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 00:32:36.605[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m26[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (2621), thread 'MainThread' (139958789662528):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m43[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f4a9be435e0>[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m26[0m, in [35mmain[0m
    [1mdf[0m [35m[1m=[0m [1mload_dataframe[0m[1m([0m[1mdonor_positive_only[0m[1m,[0m [34m[1m1[0m[1m)[0m
    [36m     â”‚              â”” [0m[36m[1marray(['CTCCGAAGTAGGATT', 'TCAGAAGGTGAGGGC', 'TTGGAAGGTTCGCAG', ...,[0m
    [36m     â”‚                [0m[36m[1m       'CCTGCTGGTACGTGG', 'TCTGCCCGTAAGCAC', 'AGGCCAGGTA...[0m
    [36m     â”” [0m[36m[1m<function load_dataframe at 0x7f4a9be3d310>[0m

  File "[32m/home/santa/2021z/uma/pro/repo/UMA_Projekt/src/miscellaneous/[0m[32m[1mdata_loader.py[0m", line [33m21[0m, in [35mload_dataframe[0m
    [1mdf[0m[35m[1m.[0m[1minsert[0m[1m([0m[1mloc[0m [35m[1m=[0m [36m"label"[0m[1m,[0m
    [36mâ”‚  â”” [0m[36m[1m<function DataFrame.insert at 0x7f4a9c2f88b0>[0m
    [36mâ”” [0m[36m[1m      0  1  2  3  4  5  6  7  8  9 10 11 12 13 14[0m
    [36m  [0m[36m[1m0     C  T  C  C  G  A  A  G  T  A  G  G  A  T  T[0m
    [36m  [0m[36m[1m1     T  C  A  G  A  A  G...[0m

  File "/home/santa/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py", line 3763, in insert
    self._mgr.insert(loc, column, value, allow_duplicates=allow_duplicates)
    â”‚    â”‚    â”‚      â”‚    â”‚       â”‚                       â”” False
    â”‚    â”‚    â”‚      â”‚    â”‚       â”” array([['1', '1', '1', ..., '1', '1', '1']], dtype=object)
    â”‚    â”‚    â”‚      â”‚    â”” '15'
    â”‚    â”‚    â”‚      â”” 'label'
    â”‚    â”‚    â”” <function BlockManager.insert at 0x7f4a9c6f49d0>
    â”‚    â”” BlockManager
    â”‚      Items: Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
    â”‚             '13', '14'],
    â”‚            dtyp...
    â””       0  1  2  3  4  5  6  7  8  9 10 11 12 13 14
      0     C  T  C  C  G  A  A  G  T  A  G  G  A  T  T
      1     T  C  A  G  A  A  G...
  File "/home/santa/anaconda3/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 1194, in insert
    raise TypeError("loc must be int")

[31m[1mTypeError[0m:[1m loc must be int[0m
[32m2022-01-30 00:32:36.803[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36m<module>[0m:[36m43[0m - [31m[1mAn error has been caught in function '<module>', process 'MainProcess' (2621), thread 'MainThread' (139958789662528):[0m
[33m[1mTraceback (most recent call last):[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m43[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f4a9be435e0>[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m28[0m, in [35mmain[0m
    [1mprint[0m[1m([0m[1mlen[0m[1m([0m[1mdf[0m[1m)[0m[1m)[0m
    [36m          â”” [0m[36m[1mNone[0m

[31m[1mTypeError[0m:[1m object of type 'NoneType' has no len()[0m
[32m2022-01-30 00:33:27.126[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 00:33:27.142[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 00:33:27.233[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m35[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 00:33:44.646[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 00:33:44.656[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 00:33:44.713[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m35[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 00:35:42.843[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 00:35:42.852[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 00:35:42.896[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m35[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 00:36:25.158[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 00:36:25.168[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 00:36:25.204[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m35[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
